on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Nix formatting
        run: |
          git ls-files -z '*.nix' | \
            xargs -0 -r nix run "https://flakehub.com/f/NixOS/nixpkgs/0.2505.808723#nixfmt-rfc-style" -- --check

      - name: Flake checks for all templates
        run: |
          shopt -s nullglob

          for flake in */flake.nix; do
            echo "Checking the template in directory ${flake}..."
            nix flake check --all-systems "./${flake}"
            echo "Successfully checked the template in ${flake} ✅"
          done

      - name: Check NixOS template
        run: |
          nix build --no-link ./nixos#nixosConfigurations.my-system.config.system.build.toplevel
