on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  template-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Nix formatting
        run: |
          git ls-files "*.nix" | \
            xargs nix run "https://flakehub.com/f/NixOS/nixpkgs/0.2505.808723#nixfmt-rfc-style" -- --check

      - name: Ensure that all templates evaluate
        run: |
          for dir in $(ls -d */); do
            (
              echo "Checking the template in directory ${dir}"
              cd $dir
              nix flake check --all-systems
              echo "Successfully checked the template in ${dir}"
            )
          done

      - name: Check Home Manager template
        run: |
          nix build --no-link --print-out-paths \
            ./home-manager#homeConfigurations.just-me-123-x86_64-linux.activationPackage

      - name: Check NixOS template
        run: |
          nix build --no-link ./nixos#nixosConfigurations.my-system.config.system.build.toplevel

  macos-checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check nix-darwin template
        run: |
          nix build --no-link --print-out-paths \
            ./nix-darwin#darwinConfigurations.just-me-123-aarch64-darwin.system

      - name: Flake checks for all templates
        run: |
          shopt -s nullglob

          for flake in */flake.nix; do
            echo "Checking the template in directory ${flake}..."
            nix flake check --all-systems "./${flake}"
            echo "Successfully checked the template in ${flake} ✅"
          done
