on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  template-checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Nix formatting
        run: |
          git ls-files -z '*.nix' | \
            xargs -0 -r nix run "https://flakehub.com/f/NixOS/nixpkgs/=0.1.883951#nixfmt" -- --check

      - name: Ensure that all templates evaluate
        run: |
          set -euo pipefail
          shopt -s nullglob

          for flake in */flake.nix; do
            dir="${flake%/flake.nix}"
            echo "Checking the template in directory ${dir}"
            nix flake check --all-systems "./${dir}"
            echo "Successfully checked the template in ${dir} ✅"
          done

      - name: Check Rust template
        run: |
          system=$(nix eval --raw --impure --expr 'builtins.currentSystem')

          echo "Building Rust dev shell 🦀"

          nix build "./rust#devShells.${system}.default"

          echo "Building Rust package 🦀"

          nix build "./rust"

          echo "Rust template OK ✅"

      - name: Check Home Manager template
        run: |
          echo "Building Home Manager activation package 🏡"

          nix build --no-link --print-out-paths \
            ./home-manager#homeConfigurations.just-me-123-x86_64-linux.activationPackage

          echo "Home Manager template OK ✅"

      - name: Check NixOS template
        run: |
          echo "Building NixOS toplevel ❄️"

          nix build --no-link --print-out-paths \
            ./nixos#nixosConfigurations.my-system.config.system.build.toplevel

          echo "NixOS template OK ✅"

  macos-checks:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check nix-darwin template
        run: |
          echo "Building nix-darwin system output 🍎"

          nix build --no-link --print-out-paths \
            ./nix-darwin#darwinConfigurations.just-me-123-aarch64-darwin.system

          echo "nix-darwin template OK ✅"
